export const mockDetails = {
  meals: [
    {
      idMeal: '53065',
      strMeal: 'Sushi',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'Japanese',
      strInstructions: ' ',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=ub68OxEypaY',
      strIngredient1: 'Sushi Rice',
      strIngredient2: 'Rice wine',
      strIngredient3: 'Caster Sugar',
      strIngredient4: 'Mayonnaise',
      strIngredient5: 'Rice wine',
      strIngredient6: 'Soy Sauce',
      strIngredient7: 'Cucumber',
      strIngredient8: ' ',
      strIngredient9: ' ',
      strIngredient10: ' ',
      strIngredient11: ' ',
      strIngredient12: ' ',
      strIngredient13: ' ',
      strIngredient14: ' ',
      strIngredient15: ' ',
      strIngredient16: ' ',
      strIngredient17: ' ',
      strIngredient18: ' ',
      strIngredient19: ' ',
      strIngredient20: ' ',
      strMeasure1: '300ml ',
      strMeasure2: '100ml',
      strMeasure3: '2 tbs',
      strMeasure4: '3 tbs',
      strMeasure5: '1 tbs',
      strMeasure6: '1 tbs',
      strMeasure7: '1',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.bbcgoodfood.com/recipes/simple-sushi',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const mockDrinks = {
  drinks: [
    {
      idDrink: '15997',
      strDrink: 'GG',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Optional alcohol',
      strGlass: 'Collins Glass',
      strInstructions: 'Pour the Galliano liqueur over ice. Fill'
      + 'the remainder of the glass with ginger'
      + 'ale and thats all there is to it. You now have a your very own GG.',
      strInstructionsES: null,
      strInstructionsFR: null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
      strIngredient1: 'Galliano',
      strIngredient2: 'Ginger ale',
      strIngredient3: 'Ice',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 1/2 shots ',
      strMeasure2: null,
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-18 22:06:00',
    },
  ],
};
